name: SwiftUIFlow CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  macos-test:
    name: Lint, Build, and Test SwiftUIFlow
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Homebrew
        run: brew update

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint (non-fatal)
        run: |
          swiftlint lint --config swiftlint.yml --reporter github-actions-logging || echo "SwiftLint warnings found"

      - name: Setup Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4"

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Clean & Build for Testing
        run: |
          scheme="SwiftUIFlow"
          xcodebuild clean build-for-testing \
            -scheme "$scheme" \
            | xcpretty

      - name: Run Tests
        run: |
          scheme="SwiftUIFlow"
          xcodebuild test-without-building \
            -scheme "$scheme" \
            | xcpretty
